# Generated by Django 3.1 on 2020-08-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('question_type', models.CharField(choices=[('One', 'Один ответ'), ('One_Text', 'Текстовый ответ'), ('Mult', 'Несколько вариантов ответа')], max_length=50)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='questionnaire.poll')),
            ],
        ),
        migrations.CreateModel(
            name='QuestAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('answer_io', models.CharField(max_length=50)),
                ('question_io', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='questionnaire.question')),
            ],
        ),
    ]
